import { Routes } from '@angular/router';
import { HomeComponent } from './home/home.component';
import { AddBlogComponent } from './add-blog/add-blog.component';
import { AddUserComponent } from './add-user/add-user.component';
import { AlertComponent } from './alert/alert.component';
import { AssignRoleComponent } from './assign-role/assign-role.component';
import { AvatarComponent } from './avatar/avatar.component';
import { BadgesComponent } from './badges/badges.component';
import { BlankPageComponent } from './blank-page/blank-page.component';
import { BlogDetailsComponent } from './blog-details/blog-details.component';
import { BlogComponent } from './blog/blog.component';
import { ButtonComponent } from './button/button.component';
import { CalendarMainComponent } from './calendar-main/calendar-main.component';
import { CalendarComponent } from './calendar/calendar.component';
import { CardComponent } from './card/card.component';
import { CarouselComponent } from './carousel/carousel.component';
import { ChatEmptyComponent } from './chat-empty/chat-empty.component';
import { ChatMessageComponent } from './chat-message/chat-message.component';
import { ChatProfileComponent } from './chat-profile/chat-profile.component';
import { CodeGeneratorNewComponent } from './code-generator-new/code-generator-new.component';
import { CodeGeneratorComponent } from './code-generator/code-generator.component';
import { ColorsComponent } from './colors/colors.component';
import { ColumnChartComponent } from './column-chart/column-chart.component';
import { ComingSoonComponent } from './coming-soon/coming-soon.component';
import { CompanyComponent } from './company/company.component';
import { CurrenciesComponent } from './currencies/currencies.component';
import { DropdownComponent } from './dropdown/dropdown.component';
import { EmailComponent } from './email/email.component';
import { ErrorComponent } from './error/error.component';
import { FaqComponent } from './faq/faq.component';
import { ForgotPasswordComponent } from './forgot-password/forgot-password.component';
import { FormLayoutComponent } from './form-layout/form-layout.component';
import { FormValidationComponent } from './form-validation/form-validation.component';
import { FormComponent } from './form/form.component';
import { GalleryComponent } from './gallery/gallery.component';
import { Home10Component } from './home-10/home-10.component';
import { Home2Component } from './home-2/home-2.component';
import { Home3Component } from './home-3/home-3.component';
import { Home4Component } from './home-4/home-4.component';
import { Home5Component } from './home-5/home-5.component';
import { Home6Component } from './home-6/home-6.component';
import { Home7Component } from './home-7/home-7.component';
import { Home8Component } from './home-8/home-8.component';
import { Home9Component } from './home-9/home-9.component';
import { ImageGeneratorComponent } from './image-generator/image-generator.component';
import { ImageUploadComponent } from './image-upload/image-upload.component';
import { InvoiceAddComponent } from './invoice-add/invoice-add.component';
import { InvoiceEditComponent } from './invoice-edit/invoice-edit.component';
import { InvoiceListComponent } from './invoice-list/invoice-list.component';
import { InvoicePreviewComponent } from './invoice-preview/invoice-preview.component';
import { KanbanComponent } from './kanban/kanban.component';
import { LanguageComponent } from './language/language.component';
import { LineChartComponent } from './line-chart/line-chart.component';
import { ListComponent } from './list/list.component';
import { MaintenanceComponent } from './maintenance/maintenance.component';
import { MarketplaceDetailsComponent } from './marketplace-details/marketplace-details.component';
import { MarketplaceComponent } from './marketplace/marketplace.component';
import { NotificationAlertComponent } from './notification-alert/notification-alert.component';
import { NotificationComponent } from './notification/notification.component';
import { PaginationComponent } from './pagination/pagination.component';
import { PaymentGatewayComponent } from './payment-gateway/payment-gateway.component';
import { PieChartComponent } from './pie-chart/pie-chart.component';
import { PortfolioComponent } from './portfolio/portfolio.component';
import { PricingComponent } from './pricing/pricing.component';
import { ProgressComponent } from './progress/progress.component';
import { RadioComponent } from './radio/radio.component';
import { RoleAccessComponent } from './role-access/role-access.component';
import { SignInComponent } from './sign-in/sign-in.component';
import { SignUpComponent } from './sign-up/sign-up.component';
import { StarRatingComponent } from './star-rating/star-rating.component';
import { StarredComponent } from './starred/starred.component';
import { SwitchComponent } from './switch/switch.component';
import { TableBasicComponent } from './table-basic/table-basic.component';
import { TableDataComponent } from './table-data/table-data.component';
import { TabsComponent } from './tabs/tabs.component';
import { TagsComponent } from './tags/tags.component';
import { TermsConditionComponent } from './terms-condition/terms-condition.component';
import { TestimonialsComponent } from './testimonials/testimonials.component';
import { TextGeneratorNewComponent } from './text-generator-new/text-generator-new.component';
import { TextGeneratorComponent } from './text-generator/text-generator.component';
import { ThemeComponent } from './theme/theme.component';
import { TooltipComponent } from './tooltip/tooltip.component';
import { TypographyComponent } from './typography/typography.component';
import { UsersGridComponent } from './users-grid/users-grid.component';
import { UsersListComponent } from './users-list/users-list.component';
import { VeiwDetailsComponent } from './veiw-details/veiw-details.component';
import { VideoGeneratorComponent } from './video-generator/video-generator.component';
import { VideosComponent } from './videos/videos.component';
import { ViewProfileComponent } from './view-profile/view-profile.component';
import { VoiceGeneratorComponent } from './voice-generator/voice-generator.component';
import { WalletComponent } from './wallet/wallet.component';
import { WidgetsComponent } from './widgets/widgets.component';
import { WizardComponent } from './wizard/wizard.component';
import { SideNavComponent } from './side-nav/side-nav.component';
import { Home11Component } from './home-11/home-11.component';
import { Home12Component } from './home-12/home-12.component';
import { Home13Component } from './home-13/home-13.component';
import { Home14Component } from './home-14/home-14.component';
import { Home15Component } from './home-15/home-15.component';
import { GalleryGridComponent } from './gallery-grid/gallery-grid.component';
import { GalleryGridDescComponent } from './gallery-grid-desc/gallery-grid-desc.component';
import { GalleryMasonryComponent } from './gallery-masonry/gallery-masonry.component';
import { GalleryHoverEffectComponent } from './gallery-hover-effect/gallery-hover-effect.component';
import { UserRolePermissionComponent } from './user-role-permission/user-role-permission.component';

export const routes: Routes = [
    {
        path: '',
        component: SideNavComponent,
        children: [
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'add-blog', component: AddBlogComponent },
            { path: 'add-user', component: AddUserComponent },
            { path: 'alert', component: AlertComponent },
            { path: 'assign-role', component: AssignRoleComponent },
            { path: 'avatar', component: AvatarComponent },
            { path: 'badges', component: BadgesComponent },
            { path: 'blank-page', component: BlankPageComponent },
            { path: 'blog-details', component: BlogDetailsComponent },
            { path: 'blog', component: BlogComponent },
            { path: 'button', component: ButtonComponent },
            { path: 'calendar-main', component: CalendarMainComponent },
            { path: 'calendar', component: CalendarComponent },
            { path: 'card', component: CardComponent },
            { path: 'carousel', component: CarouselComponent },
            { path: 'chat-empty', component: ChatEmptyComponent },
            { path: 'chat-message', component: ChatMessageComponent },
            { path: 'chat-profile', component: ChatProfileComponent },
            { path: 'code-generator-new', component: CodeGeneratorNewComponent },
            { path: 'code-generator', component: CodeGeneratorComponent },
            { path: 'colors', component: ColorsComponent },
            { path: 'column-chart', component: ColumnChartComponent },
            { path: 'company', component: CompanyComponent },
            { path: 'currencies', component: CurrenciesComponent },
            { path: 'dropdown', component: DropdownComponent },
            { path: 'email', component: EmailComponent },
            { path: 'faq', component: FaqComponent },

            { path: 'form-layout', component: FormLayoutComponent },
            { path: 'form-validation', component: FormValidationComponent },
            { path: 'form', component: FormComponent },
            { path: 'gallery-grid', component: GalleryGridComponent },
            { path: 'gallery-grid-desc', component: GalleryGridDescComponent },
            { path: 'gallery-masonry', component: GalleryMasonryComponent },
            { path: 'gallery-hover-effect', component: GalleryHoverEffectComponent },
            { path: 'image-generator', component: ImageGeneratorComponent },
            { path: 'image-upload', component: ImageUploadComponent },
            { path: 'home-10', component: Home10Component },
            { path: 'home-10', component: Home10Component },
            { path: 'home-11', component: Home11Component },
            { path: 'home-12', component: Home12Component },
            { path: 'home-13', component: Home13Component },
            { path: 'home-14', component: Home14Component },
            { path: 'home-15', component: Home15Component },
            { path: 'home-2', component: Home2Component },
            { path: 'home-3', component: Home3Component },
            { path: 'home-4', component: Home4Component },
            { path: 'home-5', component: Home5Component },
            { path: 'home-6', component: Home6Component },
            { path: 'home-7', component: Home7Component },
            { path: 'home-8', component: Home8Component },
            { path: 'home-9', component: Home9Component },
            { path: 'invoice-add', component: InvoiceAddComponent },
            { path: 'invoice-edit', component: InvoiceEditComponent },
            { path: 'invoice-list', component: InvoiceListComponent },
            { path: 'invoice-preview', component: InvoicePreviewComponent },
            { path: 'kanban', component: KanbanComponent },
            { path: 'language', component: LanguageComponent },
            { path: 'line-chart', component: LineChartComponent },
            { path: 'list', component: ListComponent },
            { path: 'marketplace-details', component: MarketplaceDetailsComponent },
            { path: 'marketplace', component: MarketplaceComponent },
            { path: 'notification-alert', component: NotificationAlertComponent },
            { path: 'notification', component: NotificationComponent },
            { path: 'pagination', component: PaginationComponent },
            { path: 'payment-gateway', component: PaymentGatewayComponent },
            { path: 'pie-chart', component: PieChartComponent },
            { path: 'portfolio', component: PortfolioComponent },
            { path: 'pricing', component: PricingComponent },
            { path: 'progress', component: ProgressComponent },
            { path: 'radio', component: RadioComponent },
            { path: 'role-access', component: RoleAccessComponent },

            { path: 'star-rating', component: StarRatingComponent },
            { path: 'starred', component: StarredComponent },
            { path: 'switch', component: SwitchComponent },
            { path: 'table-basic', component: TableBasicComponent },
            { path: 'table-data', component: TableDataComponent },
            { path: 'tabs', component: TabsComponent },
            { path: 'tags', component: TagsComponent },
            { path: 'terms-condition', component: TermsConditionComponent },
            { path: 'testimonials', component: TestimonialsComponent },
            { path: 'text-generator-new', component: TextGeneratorNewComponent },
            { path: 'text-generator', component: TextGeneratorComponent },
            { path: 'theme', component: ThemeComponent },
            { path: 'tooltip', component: TooltipComponent },
            { path: 'typography', component: TypographyComponent },
            { path: 'users-grid', component: UsersGridComponent },
            { path: 'users-list', component: UsersListComponent },
            { path: 'user-role-permission', component: UserRolePermissionComponent },
            { path: 'veiw-details', component: VeiwDetailsComponent },
            { path: 'video-generator', component: VideoGeneratorComponent },
            { path: 'videos', component: VideosComponent },
            { path: 'view-profile', component: ViewProfileComponent },
            { path: 'voice-generator', component: VoiceGeneratorComponent },
            { path: 'wallet', component: WalletComponent },
            { path: 'widgets', component: WidgetsComponent },
            { path: 'wizard', component: WizardComponent },
            { path: 'error', component: ErrorComponent },

        ]
    },
    { path: 'coming-soon', component: ComingSoonComponent },
    { path: 'maintenance', component: MaintenanceComponent },
    { path: 'sign-in', component: SignInComponent },
    { path: 'sign-up', component: SignUpComponent },
    { path: 'forgot-password', component: ForgotPasswordComponent },

    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: '**', redirectTo : 'error', pathMatch: 'full'}
];

