import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { BreadcrumbComponent } from '../breadcrumb/breadcrumb.component';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-wallet',
  standalone: true,
  imports: [BreadcrumbComponent, RouterLink,CommonModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './wallet.component.html',
  styleUrl: './wallet.component.css'
})
export class WalletComponent {
  title = 'Wallet';
  cryptoAssets= [
    {
      id: '01',
      sl: '01',
      name: 'Bitcoin',
      symbol: 'BTC',
      amount: '0.3464 BTC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: true,
      allocationPercent: 50,
      imgSrc: 'assets/images/crypto/crypto-img1.png',
    },
    {
      id: '02',
      sl: '02',
      name: 'Ethereum',
      symbol: 'ETH',
      amount: '0.5464 ETH',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: true,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img2.png',
    },
    {
      id: '03',
      sl: '03',
      name: 'Litecoin',
      symbol: 'LTC',
      amount: '0.5464 LTC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: true,
      allocationPercent: 40,
      imgSrc: 'assets/images/crypto/crypto-img3.png',
    },
    {
      id: '04',
      sl: '04',
      name: 'Binance',
      symbol: 'BNB',
      amount: '0.5464 BNB',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: true,
      allocationPercent: 70,
      imgSrc: 'assets/images/crypto/crypto-img4.png',
    },
    {
      id: '05',
      sl: '05',
      name: 'Dogecoin',
      symbol: 'DOGE',
      amount: '0.5464 DOGE',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 40,
      imgSrc: 'assets/images/crypto/crypto-img6.png',
    },
    {
      id: '06',
      sl: '06',
      name: 'Polygon',
      symbol: 'MATIC',
      amount: '0.5464 MATIC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img5.png',
    },
    // If you want to repeat Polygon multiple times with different IDs:
    {
      id: '066',
      sl: '06',
      name: 'Polygon',
      symbol: 'MATIC',
      amount: '0.5464 MATIC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img5.png',
    },
    {
      id: '016',
      sl: '06',
      name: 'Polygon',
      symbol: 'MATIC',
      amount: '0.5464 MATIC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img5.png',
    },
    {
      id: '026',
      sl: '06',
      name: 'Polygon',
      symbol: 'MATIC',
      amount: '0.5464 MATIC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img5.png',
    },
    {
      id: '061',
      sl: '06',
      name: 'Polygon',
      symbol: 'MATIC',
      amount: '0.5464 MATIC',
      price: '$2,753.00',
      changePercent: 1.37,
      isPositiveChange: false,
      allocationPercent: 80,
      imgSrc: 'assets/images/crypto/crypto-img5.png',
    },
  ];
}
